name: 'Fetch changed files in commit'
on:
  push:
jobs:
  run:
    name: test checked in file.
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '${{github.sha}}'
      - name: Get changed files
        id: changes
        run: |
          changed_file=$(git diff --name-only HEAD~1 HEAD)
          echo $changed_file
          cat $changed_file
          echo "name=all::$(git diff --name-only HEAD~1 HEAD | xargs)" >> $GITHUB_OUTPUT
          echo "name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)" >> $GITHUB_OUTPUT
          pwd
          echo Dummy
          ls
          key1Val=$(jq -r '.key1' config/testConf.json)
          echo "key1=${key1Val}" >> $GITHUB_ENV
          echo "key1=${key1Val}"
      - name: Test passed config
        id: testPassedConfig
        run: |
          echo "${{env.key1}}"


