name: 'Fetch changed files in commit'
on:
  push:
jobs:
  run:
    name: test checked in file.
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changes
        run: |
          echo ${{github.actor}}




